// components/work/case-data.ts
export type Metric = { k: string; v: string };

// Optional rich fields help render full, story‑driven case studies
export type Timeline = { kickoff: string; launch: string; weeks: number };

export type OutcomeKpi = { metric: string; before?: string; after?: string; delta?: string };
export type OutcomeVital = { k: string; v: string };
export type OutcomeLink = { label: string; href: string };
export type Testimonial = { quote: string; name: string; title: string; avatar?: string };

export type CaseItem = {
  slug: string;
  title: string;
  category: "SaaS" | "Authority" | "Storefront" | "Dashboard" | "Landing";
  lede: string;
  cover: string;         // static image shown by default
  previewMp4?: string;   // optional: hover video
  previewGif?: string;   // optional: hover gif fallback
  siteUrl?: string;      // external URL
  metrics: Metric[];     // shown as chips
  tech?: string[];       // used on detail page

  // ——— New optional, detail‑level fields for deep case studies ———
  problem?: string;          // business + UX problem we set out to solve
  goals?: string[];          // concrete, measurable objectives
  scope?: string[];          // what we shipped
  highlights?: string[];     // memorable design/engineering choices
  resultsNarrative?: string; // short paragraph tying metrics to business value
  timeline?: Timeline;       // high‑level schedule info
  services?: string[];       // capabilities involved
  roles?: string[];          // our roles on the engagement
  outcomeKpis?: OutcomeKpi[];   // headline KPI deltas for sidebar
  outcomeVitals?: OutcomeVital[]; // key vitals or flags
  outcomeWins?: string[];        // bullet wins to summarize impact
  outcomeDetails?: string[];      // richer bullets for the sidebar
  instrumentation?: string[];    // tracking/analytics and measurement wiring
  accessibility?: string[];      // a11y & SEO safeguards that shipped
  experiments?: string[];       // notable AB tests / experiments
  learnings?: string[];         // takeaways
  risks?: string[];           // risks we managed + mitigations
  links?: OutcomeLink[];        // deep links to dashboards/docs
  testimonial?: Testimonial; // optional client quote
};

export const CASES: CaseItem[] = [
  {
    slug: "aurora-finance",
    title: "Aurora Finance",
    category: "SaaS",
    lede: "Conversion‑first marketing site for a fintech SaaS. Clear value prop, razor‑fast loads.",
    cover: "/work/aurora-finance/cover.jpg",
    previewMp4: "/work/aurora-finance/preview.mp4",
    previewGif: "/work/aurora-finance/preview.gif",
    siteUrl: "#",
    metrics: [{ k: "LCP", v: "1.2s" }, { k: "+conv", v: "32%" }, { k: "CLS", v: "0.00" }],
    tech: ["Next.js", "Tailwind", "Vercel Analytics", "Schema.org"],
    problem: "Low trial conversion due to unclear messaging and slow hero paint on mobile (3.3s LCP baseline).",
    goals: [
      "Clarify positioning in first screenful",
      "Hit sub‑1.5s LCP on 4G",
      "Add credible proof and compliant pricing",
    ],
    scope: [
      "Narrative & IA refresh",
      "Design system tokens + components",
      "Next.js rebuild with edge caching",
      "Analytics events & funnel dashboards",
      "Schema.org FAQ & pricing",
    ],
    highlights: [
      "Above‑the‑fold payload under 85KB",
      "Responsive proof band with regulated disclaimers",
      "One‑tap demo CTA with calendaring deep link",
    ],
    resultsNarrative:
      "Trials lifted 32% after launch with materially faster first paint and tighter story; sales noted fewer clarification calls.",
    timeline: { kickoff: "2025-02-10", launch: "2025-03-07", weeks: 4 },
    services: ["Strategy", "Brand Copy", "Web Design", "Frontend", "Analytics", "SEO"],
    roles: ["Strategy", "Design", "Frontend", "Analytics"],
    outcomeKpis: [
      { metric: "Trials", before: "2.4%", after: "3.2%", delta: "+32%" },
      { metric: "Hero LCP", before: "3.3s", after: "1.2s" },
      { metric: "Bounce", before: "47%", after: "39%" },
    ],
    outcomeVitals: [
      { k: "LCP", v: "1.2s" },
      { k: "CLS", v: "0.00" },
      { k: "TTFB", v: "95ms" },
    ],
    experiments: [
      "Headline: benefit vs. category label",
      "Proof band order (logos → quotes)",
      "Hero media format (AVIF vs. WEBP)",
    ],
    learnings: [
      "Short, outcome‑led hero copy lifted primary CTA clicks by 18%.",
      "Regulatory disclaimers in a collapsible kept trust high without adding noise.",
    ],
    risks: [
      "Compliance/wording risk in financial claims — mitigated via legal review and collapsible disclaimers.",
      "Performance regression risk — guarded with Lighthouse CI and performance budgets in PR checks.",
    ],
    testimonial: {
      quote:
        "The first impression finally matches the product. Load times and clarity both improved — trials went up immediately.",
      name: "Amelie Tran",
      title: "Head of Growth, Aurora Finance",
      avatar: "https://randomuser.me/api/portraits/women/68.jpg",
    },
    outcomeWins: [
      "↑ +32% trial starts within 30 days",
      "Hero LCP cut from 3.3s → 1.2s on 4G",
      "Fewer clarification calls reported by sales",
    ],
    outcomeDetails: [
      "Positioning clarified in under 10 words",
      "FAQ schema surfaced sitelinks for pricing & docs",
      "Calendly deep links lifted booked demos",
      "Hero media shipped as AVIF under 60KB",
      "Edge caching kept TTFB under 100ms regionally",
      "Heatmaps + scroll depth informed hero layout tweaks",
      "Legal review cadence kept compliance copy crisp without friction"
    ],
    instrumentation: [
      "GA4 with funnel + UTM normalization",
      "Vercel Analytics RUM dashboards",
      "Search Console integration & sitemaps",
      "BigQuery export for weekly cohort reports",
    ],
    accessibility: [
      "Logical heading order & landmarks",
      "High‑contrast palette with focus rings",
      "Alt text & aria‑labels on proof band",
      "Skip link and keyboard‑first nav",
    ],
  },
  {
    slug: "atelier-studio",
    title: "Atelier Studio",
    category: "Authority",
    lede: "Elegant 5‑page authority site with blog & lead magnet. Built to rank and convert.",
    cover: "/work/atelier-studio/cover.jpg",
    previewMp4: "/work/atelier-studio/preview.mp4",
    previewGif: "/work/atelier-studio/preview.gif",
    siteUrl: "#",
    metrics: [{ k: "Organic", v: "+41%" }, { k: "Bounce", v: "−18%" }, { k: "Forms", v: "+2.2×" }],
    tech: ["Next.js", "MDX", "Sitemap", "OG tags"],
    problem: "Publishing cadence was stalled and off‑brand pages were diluting search intent.",
    goals: ["Codify tone & brand system", "Launch editorial CMS", "Capture 3 bottom‑funnel terms"],
    scope: [
      "Brand kit + typography scale",
      "MDX blog with editorial checklist",
      "Lead magnet + email capture",
      "Author pages & schema",
    ],
    highlights: [
      "Reusable page sections with guardrails",
      "Editorial scorecard at publish time",
      "Hover‑to‑preview work reel on homepage",
    ],
    resultsNarrative:
      "Within six weeks, organic sessions rose 41% and bounce dropped 18% as content matched intent and pages shipped faster.",
    timeline: { kickoff: "2025-01-15", launch: "2025-02-28", weeks: 6 },
    services: ["Brand", "Web Design", "Frontend", "Content", "SEO"],
    roles: ["Design", "Frontend", "SEO"],
    outcomeKpis: [
      { metric: "Organic sessions", before: "—", after: "+41%" },
      { metric: "Bounce", before: "—", after: "−18%" },
      { metric: "Form submits", before: "—", after: "2.2×" },
    ],
    outcomeVitals: [
      { k: "CWV", v: "Green" },
      { k: "Indexables", v: "100%" },
    ],
    experiments: [
      "Title format test on articles",
      "Lead magnet art vs. photo",
      "CTA placement inside articles",
    ],
    learnings: [
      "Consistency in headings improves scan and reduces pogo‑sticking.",
      "Editorial checklist reduced publish mistakes to near‑zero.",
    ],
    risks: [
      "SEO cannibalization from overlapping topics — mitigated with canonical tags and keyword map.",
      "Editorial drift from brand voice — mitigated by the publish‑time checklist.",
    ],
    testimonial: {
      quote: "Publishing is finally easy — and on brand. Leads from content doubled in a month.",
      name: "Clara Rossi",
      title: "Creative Director, Atelier Studio",
      avatar: "https://randomuser.me/api/portraits/women/65.jpg",
    },
    outcomeWins: [
      "Organic sessions ↑ 41% in six weeks",
      "Bounce reduced 18% with clearer IA",
      "Form submissions 2.2× via lead magnet",
    ],
    outcomeDetails: [
      "MDX + checklist cut publish time by ~40%",
      "Author pages created internal link hubs",
      "Lead magnet nurtures bottom‑funnel topics",
      "Search Console showed faster indexing & coverage",
      "Reusable sections reduced design drift",
      "Topic clusters connected pillar pages to supporting posts",
      "Automatic image compression kept blog assets lightweight"
    ],
    instrumentation: [
      "GA4 content groupings + scroll depth",
      "404/500 Slack alerts via Edge logs",
      "Search Console + XML sitemaps",
    ],
    accessibility: [
      "Readable line length & link underlines",
      "Descriptive alt text for portfolio tiles",
      "ARIA labels for pagination and filters",
    ],
  },
  {
    slug: "swiftcart",
    title: "SwiftCart",
    category: "Storefront",
    lede: "Perf‑tuned D2C storefront with Razorpay checkout. Premium visuals, lightweight code.",
    cover: "/work/swiftcart/cover.jpg",
    previewMp4: "/work/swiftcart/preview.mp4",
    previewGif: "/work/swiftcart/preview.gif",
    siteUrl: "#",
    metrics: [{ k: "LCP", v: "1.4s" }, { k: "CR", v: "+19%" }, { k: "AOV", v: "+12%" }],
    tech: ["Next.js", "Razorpay", "ISR"],
    problem: "Slow PDPs and friction at checkout were suppressing revenue on mobile.",
    goals: ["1.5s LCP on PDPs", "Reduce checkout steps to 2", "Lift CR by 10%+"],
    scope: ["Edge‑cached catalog", "Faceted search", "One‑page Razorpay", "Cart recovery events"],
    highlights: [
      "Above‑the‑fold image CDN with art‑direction presets",
      "Schema for products, offers, and reviews",
      "Back‑in‑stock + abandoned cart flows",
    ],
    resultsNarrative:
      "Conversion rose 19% and AOV 12% with faster PDPs and fewer clicks to pay.",
    timeline: { kickoff: "2024-11-04", launch: "2024-12-16", weeks: 6 },
    services: ["Storefront", "Frontend", "Payments", "Analytics", "SEO"],
    roles: ["Design", "Frontend", "Analytics"],
    outcomeKpis: [
      { metric: "CR", before: "2.6%", after: "3.1%", delta: "+19%" },
      { metric: "AOV", before: "₹1,980", after: "₹2,220", delta: "+12%" },
      { metric: "PDP LCP", before: "2.8s", after: "1.4s" },
    ],
    outcomeVitals: [ { k: "FCP", v: "0.9s" }, { k: "TTFB", v: "80ms" } ],
    experiments: [
      "Image format (AVIF vs. WEBP)",
      "Checkout step consolidation",
      "Cart recovery timing (1h vs. 24h)",
    ],
    learnings: [
      "Bigger, faster thumbnails helped filter engagement without hurting load.",
      "One‑page Razorpay flow outperformed multi‑step by 11%.",
    ],
    risks: [
      "Checkout changes impacting conversions — mitigated with staged rollout and instant rollback.",
      "Payment failures during transition — monitored via Razorpay webhooks and alerts.",
    ],
    testimonial: {
      quote: "Mobile checkout feels effortless now. Faster PDPs and the one-page flow lifted revenue within days.",
      name: "Rohan Mehta",
      title: "Head of Ecommerce, SwiftCart",
      avatar: "https://randomuser.me/api/portraits/men/62.jpg",
    },
    outcomeWins: [
      "CR +19% and AOV +12% post‑launch",
      "PDP LCP 2.8s → 1.4s",
      "Cart recovery flows revived dormant revenue",
    ],
    outcomeDetails: [
      "Above‑the‑fold images served via AVIF with art‑direction",
      "One‑page Razorpay reduced drop‑offs between steps",
      "Faceted search powered by Insights improved findability",
      "Server‑side Purchase events de‑duped for accuracy",
      "Cart recovery and back‑in‑stock flows re‑engaged buyers",
      "Lazy‑hydrated PDP widgets reduced JS cost below the fold",
      "Address validation at checkout reduced error loops"
    ],
    instrumentation: [
      "GA4 Enhanced Ecommerce (server‑side)",
      "Razorpay webhooks mapped to Purchase events",
      "Price/variant view + AddToCart events",
    ],
    accessibility: [
      "Accessible form inputs with inline errors",
      "Live region updates for cart totals",
      "Keyboard‑friendly gallery & zoom",
    ],
  },
  {
    slug: "quartz-analytics",
    title: "Quartz Analytics",
    category: "Dashboard",
    lede: "Role‑based admin with clean data flows. Accessible components and dark‑mode ready.",
    cover: "/work/quartz-analytics/cover.jpg",
    previewMp4: "/work/quartz-analytics/preview.mp4",
    previewGif: "/work/quartz-analytics/preview.gif",
    siteUrl: "#",
    metrics: [{ k: "Tickets", v: "−34%" }, { k: "NPS", v: "9.1" }, { k: "Uptime", v: "99.9%" }],
    tech: ["Next.js", "tRPC/REST", "Auth", "Charts"],
    problem: "Operators couldn’t complete key workflows without bouncing between tools.",
    goals: ["Unify reporting", "Keyboard‑first UX", "AA accessibility"],
    scope: ["RBAC & audit logs", "Inline edit tables", "Charts & alerts", "Dark mode"],
    highlights: [
      "Latency‑aware loading states",
      "Command‑palette for power users",
      "Semantic tables with sticky columns",
    ],
    resultsNarrative: "Support tickets fell by a third and power users rated the new flows highly (NPS 9.1).",
    timeline: { kickoff: "2024-09-09", launch: "2024-10-28", weeks: 7 },
    services: ["Product Design", "Frontend", "Backend", "QA"],
    roles: ["Design", "Frontend", "Backend"],
    outcomeKpis: [
      { metric: "Support tickets", before: "—", after: "−34%" },
      { metric: "NPS", before: "7.8", after: "9.1" },
      { metric: "Task completion time", before: "—", after: "−22%" },
    ],
    outcomeVitals: [ { k: "TTI", v: "1.0s" }, { k: "A11y", v: "AA" } ],
    experiments: [
      "Table density presets",
      "Sticky columns vs. wrap",
      "Command palette discoverability tooltip",
    ],
    learnings: [
      "Keyboardable commands increased completion for power users.",
      "Inline edits with optimistic UI reduced modal churn.",
    ],
    risks: [
      "RBAC permission regressions — mitigated with permission tests and audit logs.",
      "Data freshness across charts — mitigated using background polling + stale‑while‑revalidate.",
    ],
    testimonial: {
      quote: "The new dashboards are fast and predictable. Tickets dropped and our team finally trusts the data.",
      name: "Natalie Pierce",
      title: "Operations Director, Quartz Analytics",
      avatar: "https://randomuser.me/api/portraits/women/21.jpg",
    },
    outcomeWins: [
      "Support tickets −34% QoQ",
      "NPS improved from 7.8 → 9.1",
      "99.9% uptime with graceful degradation",
    ],
    outcomeDetails: [
      "Command‑palette sped up expert workflows",
      "Optimistic inline edits reduced modal churn",
      "Sticky columns preserved context for wide tables",
      "Dark‑mode parity with AA contrast",
      "Trace data mapped to SLOs for reliability reviews",
      "Role‑aware empty states prevented dead‑end screens",
      "Background polling with SWR kept charts fresh without jank"
    ],
    instrumentation: [
      "OpenTelemetry tracing for key flows",
      "Sentry error tracking + release health",
      "Role‑based audit logs & usage metrics",
    ],
    accessibility: [
      "AA contrast with dark mode parity",
      "Keyboard navigation and skip targets",
      "Data table semantics with screen‑reader summaries",
    ],
  },
  {
    slug: "lift",
    title: "Lift",
    category: "Landing",
    lede: "Crisp landing sprint. Message clarity, proof, and single, unmistakable CTA.",
    cover: "/work/lift/cover.jpg",
    previewMp4: "/work/lift/preview.mp4",
    previewGif: "/work/lift/preview.gif",
    siteUrl: "#",
    metrics: [{ k: "TTFB", v: "70ms" }, { k: "Leads", v: "+2.8×" }],
    tech: ["Next.js", "Edge", "Analytics"],
    problem: "Crowded hero and multiple CTAs reduced clarity and hurt lead capture.",
    goals: ["One primary action", "Proof above the fold", "<100KB critical path"],
    scope: ["Narrative", "Hero redesign", "Case band", "Contact flow"],
    highlights: ["Animated metrics reel", "Edge cached HTML", "High‑contrast a11y"],
    resultsNarrative: "Leads per visit nearly tripled; most conversions happen in the first screenful now.",
    timeline: { kickoff: "2025-03-03", launch: "2025-03-10", weeks: 1 },
    services: ["Copy", "Design", "Frontend"],
    roles: ["Strategy", "Design", "Frontend"],
    outcomeKpis: [
      { metric: "TTFB", before: "180ms", after: "70ms" },
      { metric: "Leads/visit", before: "1×", after: "2.8×" },
      { metric: "Hero CTR", before: "—", after: "+24%" },
    ],
    outcomeVitals: [ { k: "CLS", v: "0.00" } ],
    experiments: [
      "CTA label test",
      "Logo band vs. quote first",
      "Proof order (logos vs. quotes)",
    ],
    learnings: [ "Single CTA + succinct hero outperformed variants with secondary actions." ],
    risks: [
      "Translation inaccuracies across locales — mitigated via glossary and reviewer workflow.",
      "Duplicate content between markets — mitigated with hreflang and canonical rules.",
    ],
    outcomeWins: [
      "Leads/visit improved to 2.8×",
      "TTFB dropped to 70ms via Edge",
      "CTA clarity reduced confusion clicks",
    ],
    outcomeDetails: [
      "Single CTA eliminated decision friction",
      "Proof band above the fold increased trust",
      "Edge‑cached HTML improved TTFB across regions",
      "Privacy‑safe analytics validated variant wins",
      "Zero CLS preserved visual stability on load",
      "Deferred loading for below‑fold media minimized JS work",
      "Ad scent preserved via aligned microcopy from campaigns"
    ],
    testimonial: {
      quote: "The message is instant and the single CTA works. Lead quality and volume jumped right away.",
      name: "Aarav Kapoor",
      title: "Founder, Lift",
      avatar: "https://randomuser.me/api/portraits/men/19.jpg",
    },
    instrumentation: [
      "GA4 funnel events (HeroCTA, ProofClick)",
      "Privacy‑safe session replay (masked)",
      "AB test results exported to Looker",
    ],
    accessibility: [
      "Reduced motion for prefers‑reduced‑motion",
      "Visible focus states & semantic buttons",
      "Zero layout shift (CLS 0.00)",
    ],
  },
  {
    slug: "northbound",
    title: "Northbound",
    category: "Authority",
    lede: "International site with schema & editorial system. Calm, luxurious UI.",
    cover: "/work/northbound/cover.jpg",
    previewMp4: "/work/northbound/preview.mp4",
    previewGif: "/work/northbound/preview.gif",
    siteUrl: "#",
    metrics: [{ k: "Foundations", v: "SEO" }, { k: "CWV", v: "Green" }, { k: "Forms", v: "+63%" }],
    tech: ["Next.js", "MDX", "i18n"],
    problem: "Fragmented locales and duplicated content made global rollout hard.",
    goals: ["Single content model", "Schema coverage", "Core Web Vitals green"],
    scope: ["i18n routing", "Locale‑aware sitemap", "Authoring roles", "Forms & CRM"],
    highlights: ["Glossary with canonical tags", "Translation fallbacks", "Image art‑direction"],
    resultsNarrative: "Green CWV across markets and a 63% lift in qualified forms after launch.",
    timeline: { kickoff: "2024-10-21", launch: "2024-12-09", weeks: 7 },
    services: ["Web", "Content", "SEO"],
    roles: ["Design", "Frontend", "SEO"],
    outcomeKpis: [
      { metric: "Qualified forms", before: "—", after: "+63%" },
      { metric: "i18n coverage", before: "3 locales", after: "6 locales" },
      { metric: "Avg indexing time", before: "7d", after: "2d", delta: "−71%" },
    ],
    outcomeVitals: [ { k: "CWV", v: "Green" } ],
    experiments: [
      "Glossary placement",
      "CTA copy per‑locale",
      "Localized proof ordering",
    ],
    learnings: [ "Shared content model prevented duplication and eased translation." ],
    risks: [
      "Noisy alerting fatiguing on‑call — mitigated by sane defaults, rate limits and quiet hours.",
      "WebSocket disconnect loops — mitigated with exponential backoff and heartbeat.",
    ],
    outcomeWins: [
      "Qualified forms +63% across locales",
      "CWV green across 6 regions",
      "Single content model reduced duplication",
    ],
    outcomeDetails: [
      "Shared content model prevented duplication",
      "Glossary + canonicals reduced keyword cannibalization",
      "Image art‑direction improved LCP without losing quality",
      "Localized sitemaps accelerated coverage",
      "Per‑locale dashboards clarified performance by region",
      "Hreflang/alternate tags increased international CTR",
      "Authoring roles shortened approvals and reduced drift"
    ],
    testimonial: {
      quote: "Global launch was smooth. Editors move faster and qualified form fills are way up.",
      name: "Elise Dubois",
      title: "Marketing Lead, Northbound",
      avatar: "https://randomuser.me/api/portraits/women/54.jpg",
    },
    instrumentation: [
      "Locale roll‑up GA4 + per‑locale views",
      "Hreflang + localized sitemaps",
      "Search Console properties per locale",
    ],
    accessibility: [
      "Accessible language switcher with aria‑current",
      "Lang attributes & localized date formats",
      "Alt text and captions for imagery",
    ],
  },
  {
    slug: "vista-ops",
    title: "Vista Ops",
    category: "Dashboard",
    lede: "Operational dashboard with real‑time insights and sensible defaults.",
    cover: "/work/vista-ops/cover.jpg",
    previewMp4: "/work/vista-ops/preview.mp4",
    previewGif: "/work/vista-ops/preview.gif",
    siteUrl: "#",
    metrics: [{ k: "Errors", v: "−47%" }, { k: "TTI", v: "1.1s" }],
    tech: ["Next.js", "WebSockets", "RSC"],
    problem: "Teams lacked shared visibility on live operations and error budgets.",
    goals: ["Critical metrics at a glance", "<1.2s interactive", "Default alert rules"],
    scope: ["Real‑time widgets", "RBAC", "Incident timeline", "Exportable reports"],
    highlights: ["WebSocket streams with backoff", "Compact grid density", "Keyboard triage"],
    resultsNarrative: "On‑call load decreased as defaults caught more issues early; error rate dropped 47%.",
    timeline: { kickoff: "2025-01-06", launch: "2025-02-10", weeks: 5 },
    services: ["Product", "Frontend", "Backend"],
    roles: ["Design", "Frontend", "Backend"],
    outcomeKpis: [
      { metric: "Error rate", before: "—", after: "−47%" },
      { metric: "On‑call pages", before: "—", after: "−18%" },
      { metric: "MTTA", before: "13m", after: "8m", delta: "−38%" },
    ],
    outcomeVitals: [ { k: "TTI", v: "1.1s" } ],
    experiments: [
      "Widget density presets",
      "Default alert rules",
      "Incident digest cadence (hourly vs. daily)",
    ],
    learnings: [ "Sane defaults catch most issues before escalation." ],
    risks: [
      "Aggressive typo tolerance returning irrelevant results — mitigated with synonym curation and analytics.",
      "ISR cache staleness on fast‑moving SKUs — mitigated with on‑demand revalidation.",
    ],
    outcomeWins: [
      "Error rate −47% after sane defaults",
      "On‑call pages −18% with earlier signals",
      "TTI stabilized at 1.1s under load",
    ],
    outcomeDetails: [
      "WebSocket streams with heartbeat & backoff",
      "Default alert rules reduced noisy paging",
      "Compact grid density boosted info density",
      "Exportable reports aligned teams in postmortems",
      "RBAC ensured the right visibility per role",
      "Incident timeline clarified ownership handoffs",
      "Digest emails summarized key shifts for leadership"
    ],
    testimonial: {
      quote: "We catch issues earlier with sane defaults and real-time views. On-call is quieter and calmer.",
      name: "Kenji Sato",
      title: "SRE Manager, Vista Ops",
      avatar: "https://randomuser.me/api/portraits/men/23.jpg",
    },
    instrumentation: [
      "WebSocket heartbeat metrics",
      "Sentry + uptime checks routed to Slack",
      "RBAC audit trails for incident reviews",
    ],
    accessibility: [
      "Keyboard triage and focus management",
      "Color‑safe status badges",
      "ARIA live updates for incident feed",
    ],
  },
  {
    slug: "ember-outlet",
    title: "Ember Outlet",
    category: "Storefront",
    lede: "Catalog that feels like an app. Smooth filters, fast product pages.",
    cover: "/work/ember-outlet/cover.jpg",
    previewMp4: "/work/ember-outlet/preview.mp4",
    previewGif: "/work/ember-outlet/preview.gif",
    siteUrl: "#",
    metrics: [{ k: "FCP", v: "0.9s" }, { k: "CR", v: "+23%" }],
    tech: ["Next.js", "ISR", "Algolia"],
    problem: "Legacy storefront felt sluggish and search didn’t tolerate typos.",
    goals: ["<1s FCP on catalog", "Instant filters", "Better zero‑results UX"],
    scope: ["Algolia search", "ISR for PDPs", "Sticky cart", "Structured data"],
    highlights: ["Facet analytics to tune filters", "Auto‑suggest + synonyms", "Optimized image sets"],
    resultsNarrative: "Shoppers found products faster and converted 23% more often.",
    timeline: { kickoff: "2024-08-12", launch: "2024-09-23", weeks: 6 },
    services: ["Storefront", "Frontend", "Search", "SEO"],
    roles: ["Frontend", "SEO"],
    outcomeKpis: [
      { metric: "FCP", before: "1.7s", after: "0.9s" },
      { metric: "CR", before: "—", after: "+23%" },
      { metric: "Zero‑results rate", before: "7.4%", after: "3.1%", delta: "−58%" },
    ],
    outcomeVitals: [ { k: "CLS", v: "0.01" } ],
    experiments: [
      "Facet order",
      "Typo tolerance levels",
      "Sticky cart vs. floating cart",
    ],
    learnings: [ "Better zero‑results UX preserved momentum in browse sessions." ],
    risks: [
      "AB test novelty bias — mitigated with 2‑week run and equal traffic split.",
      "Attribution noise from simultaneous campaigns — mitigated via UTM normalization.",
    ],
    outcomeWins: [
      "FCP down to 0.9s on catalog",
      "CR +23% with smoother filters",
      "Zero‑results UX preserved browse intent",
    ],
    outcomeDetails: [
      "Algolia synonyms improved zero‑results recovery",
      "Sticky cart increased add‑to‑cart continuation",
      "ISR kept PDPs fresh without cold starts",
      "Facet analytics guided better filter ordering",
      "Structured data improved product rich results",
      "Preconnect hints sped up CDN asset fetches",
      "Variant image sets optimized with AVIF/WEBP fallbacks"
    ],
    testimonial: {
      quote: "Browsing feels like an app. Filters are instant, PDPs are quick, and conversion is up.",
      name: "Sofia Marin",
      title: "GM, Ember Outlet",
      avatar: "https://randomuser.me/api/portraits/women/47.jpg",
    },
    instrumentation: [
      "Algolia Insights (view/click/convert)",
      "GA4 Ecommerce with server‑to‑server Purchase",
      "Zero‑results + facet usage events",
    ],
    accessibility: [
      "Fieldset/legend for filter groups",
      "Keyboard operable chips and checkboxes",
      "Live region for mini‑cart updates",
    ],
  },
  {
    slug: "signal",
    title: "Signal",
    category: "Landing",
    lede: "A/B‑tested hero & proof band. Designed to sell the story in seconds.",
    cover: "/work/signal/cover.jpg",
    previewMp4: "/work/signal/preview.mp4",
    previewGif: "/work/signal/preview.gif",
    siteUrl: "#",
    metrics: [{ k: "LCP", v: "1.0s" }, { k: "Signups", v: "+38%" }],
    tech: ["Next.js", "Experimentation", "Analytics"],
    problem: "Audience didn’t understand the offer quickly enough to act.",
    goals: ["Win the first 5 seconds", "Proof above fold", "Measure with AB"],
    scope: ["Messaging sprint", "Hero variants", "Testimonials", "AB test wiring"],
    highlights: ["Lightweight animations", "Stable layout (0 CLS)", "Quote carousel"],
    resultsNarrative: "The winning variant communicated faster and unlocked 38% more signups.",
    timeline: { kickoff: "2025-04-07", launch: "2025-04-21", weeks: 2 },
    services: ["Copy", "Design", "Frontend", "Experimentation"],
    roles: ["Strategy", "Design", "Frontend"],
    outcomeKpis: [
      { metric: "LCP", before: "1.6s", after: "1.0s" },
      { metric: "Signups", before: "—", after: "+38%" },
      { metric: "Hero CTR", before: "—", after: "+22%" },
    ],
    outcomeVitals: [ { k: "CLS", v: "0.00" } ],
    experiments: [
      "Hero message variants",
      "Proof order",
      "CTA label clarity",
    ],
    learnings: [ "Narrative that states the outcome first wins the first 5 seconds." ],
    risks: [
      "Pricing misconceptions for high‑volume tiers — mitigated with usage examples and tooltips.",
      "Docs gateway increasing bounce — mitigated by prefetch and clear back‑to‑pricing affordances.",
    ],
    outcomeWins: [
      "Signups +38% from winning variant",
      "Hero LCP 1.6s → 1.0s",
      "Proof band increased trust signals",
    ],
    outcomeDetails: [
      "Outcome‑first headline won AB test",
      "Proof order fine‑tuned via experimentation",
      "Lightweight animations respected reduced‑motion",
      "Zero CLS preserved layout stability",
      "Experiment exposure events audited variants",
      "Sampled session replay pinpointed friction spots",
      "Sprite/inline proof assets reduced LCP cost"
    ],
    testimonial: {
      quote: "The winning hero communicates in seconds. Signups climbed and the proof band builds trust.",
      name: "Daniel Cho",
      title: "Growth PM, Signal",
      avatar: "https://randomuser.me/api/portraits/men/12.jpg",
    },
    instrumentation: [
      "AB framework with redirect‑safe hashing",
      "GA4 conversions + pixel sync",
      "Experiment exposure events",
    ],
    accessibility: [
      "Carousel announced via aria‑live",
      "Prefers‑reduced‑motion respected",
      "High‑contrast focusable controls",
    ],
  },
  {
    slug: "atlas-pay",
    title: "Atlas Pay",
    category: "SaaS",
    lede: "Pricing‑focused funnel for a B2B payments API. Clear docs entry, demo CTA, and schema‑rich FAQs.",
    cover: "/work/atlas-pay/cover.jpg",
    previewMp4: "/work/atlas-pay/preview.mp4",
    previewGif: "/work/atlas-pay/preview.gif",
    siteUrl: "#",
    metrics: [{ k: "LCP", v: "1.1s" }, { k: "Demos", v: "+28%" }, { k: "CLS", v: "0.01" }],
    tech: ["Next.js", "Tailwind", "OpenAPI", "PostHog", "Schema.org"],
    problem: "Prospects jumped straight to docs without understanding pricing and compliance tiers.",
    goals: ["Clarify pricing", "Trust badges", "Short path to demo"],
    scope: ["Pricing table", "FAQ schema", "Docs gateway", "Tracking plan"],
    highlights: ["Usage slider tied to pricing", "SOC2 badges", "Docset prefetch"],
    resultsNarrative: "Demo requests increased 28% as buyers self‑qualified faster.",
    timeline: { kickoff: "2025-02-03", launch: "2025-03-14", weeks: 5 },
    services: ["Web", "Analytics", "SEO"],
    roles: ["Design", "Frontend", "Analytics"],
    outcomeKpis: [
      { metric: "Demo requests", before: "—", after: "+28%" },
      { metric: "Hero LCP", before: "2.2s", after: "1.1s" },
      { metric: "Docs bounce", before: "56%", after: "42%", delta: "−25%" },
    ],
    outcomeVitals: [ { k: "CLS", v: "0.01" } ],
    experiments: [
      "Pricing slider labels",
      "Badge placement",
      "Demo CTA placement",
    ],
    learnings: [ "Transparent tiers speed up self‑qualification for buyers." ],
    risks: [
      "HIPAA/privacy concerns with analytics — mitigated via proxy‑mode tracking and masking.",
      "Scheduling vendor outages — mitigated with status checks and phone fallback.",
    ],
    outcomeWins: [
      "Demo requests +28% post‑pricing revamp",
      "Hero LCP cut to 1.1s",
      "Docs gateway reduced misroutes",
    ],
    outcomeDetails: [
      "Usage slider explained tier breakpoints",
      "SOC2 & compliance badges increased trust",
      "Prefetched docs reduced back‑and‑forth hops",
      "Proxy‑mode analytics kept PII out of logs",
      "CRM handoff tagged lead quality for sales",
      "Calculator presets covered common volume scenarios",
      "FAQ schema rich results expanded SERP real estate"
    ],
    testimonial: {
      quote: "Pricing is finally clear. More buyers request demos and the docs gateway reduced dead-ends.",
      name: "Priya Nair",
      title: "VP Growth, Atlas Pay",
      avatar: "https://randomuser.me/api/portraits/women/39.jpg",
    },
    instrumentation: [
      "GA4 + PostHog with pricing slider events",
      "Docs gateway click mapping",
      "CRM handoff via webhook (lead quality tags)",
    ],
    accessibility: [
      "Copy‑code buttons with aria‑live",
      "Table headers/ids for pricing matrices",
      "Badge icons labeled for screen readers",
    ],
  },
  {
    slug: "harbor-health",
    title: "Harbor Health",
    category: "Authority",
    lede: "Modern healthcare authority site with booking, rich FAQs, and HIPAA‑friendly flows.",
    cover: "/work/harbor-health/cover.jpg",
    previewMp4: "/work/harbor-health/preview.mp4",
    previewGif: "/work/harbor-health/preview.gif",
    siteUrl: "#",
    metrics: [{ k: "Organic", v: "+52%" }, { k: "Bounce", v: "−22%" }, { k: "Appointments", v: "+1.9×" }],
    tech: ["Next.js", "MDX", "Schema.org", "Forms"],
    problem: "Patients struggled to find services and book from mobile.",
    goals: ["Clear service IA", "Mobile first", "ADA AA"],
    scope: ["Services hub", "Physician bio schema", "Booking integration", "Content model"],
    highlights: ["Care pathways by condition", "Sticky booking", "Rich FAQ schema"],
    resultsNarrative: "Appointment starts nearly doubled as navigation and content became clearer.",
    timeline: { kickoff: "2024-07-01", launch: "2024-08-19", weeks: 7 },
    services: ["Web", "Content", "SEO", "Accessibility"],
    roles: ["Design", "Frontend", "SEO"],
    outcomeKpis: [
      { metric: "Organic", before: "—", after: "+52%" },
      { metric: "Bounce", before: "—", after: "−22%" },
      { metric: "Appt starts", before: "—", after: "1.9×" },
    ],
    outcomeVitals: [ { k: "A11y", v: "AA" } ],
    experiments: [
      "Sticky booking on mobile",
      "FAQ ordering",
      "Care pathway ordering by condition",
    ],
    learnings: [ "Clear care pathways increase task success for patients." ],
    risks: [
      "Docs churn causing broken links — mitigated by versioned docs and redirects.",
      "High bounce from long pages — mitigated with sticky ToC and section summaries.",
    ],
    outcomeWins: [
      "Appointments +1.9× on mobile",
      "Organic +52%, Bounce −22%",
      "Sticky booking improved task success",
    ],
    outcomeDetails: [
      "Care pathways by condition reduced confusion",
      "Sticky booking boosted mobile completion",
      "Physician schema improved visibility in SERP",
      "Proxy‑mode analytics met HIPAA expectations",
      "Call tracking linked campaigns to bookings",
      "Location schema supported stronger local pack performance",
      "AA‑grade contrast system applied across components"
    ],
    testimonial: {
      quote: "Patients find services faster and book from mobile without friction. The content is clear and compliant.",
      name: "Dr. Laila Rahman",
      title: "Clinical Lead, Harbor Health",
      avatar: "https://randomuser.me/api/portraits/women/72.jpg",
    },
    instrumentation: [
      "Proxy‑mode analytics (HIPAA‑friendly)",
      "GA4 events for booking funnel",
      "Call tracking numbers with source tagging",
    ],
    accessibility: [
      "AA compliant forms & error messaging",
      "Large tap targets and readable copy",
      "Rich FAQ schema for assistive tech",
    ],
  },
  {
    slug: "nova-learning",
    title: "Nova Learning",
    category: "SaaS",
    lede: "Course platform marketing with crisp messaging, fast docs, and conversion‑focused CTAs.",
    cover: "/work/nova-learning/cover.jpg",
    previewMp4: "/work/nova-learning/preview.mp4",
    previewGif: "/work/nova-learning/preview.gif",
    siteUrl: "#",
    metrics: [{ k: "LCP", v: "1.0s" }, { k: "Signups", v: "+35%" }, { k: "CLS", v: "0.00" }],
    tech: ["Next.js", "Tailwind", "Vercel Analytics", "MDX"],
    problem: "Value prop buried behind feature lists; docs were slow to navigate.",
    goals: ["Message clarity", "Fast docs", "Lower support load"],
    scope: ["Narrative redesign", "Docs IA", "Guided CTA flow", "Event tracking"],
    highlights: ["Copy table stakes vs. differentiators", "Sticky table of contents", "Zero‑layout shift"],
    resultsNarrative: "Signups rose 35% and support saw fewer basic questions thanks to improved docs.",
    timeline: { kickoff: "2025-01-20", launch: "2025-02-24", weeks: 5 },
    services: ["Strategy", "Web", "Docs", "Analytics"],
    roles: ["Strategy", "Design", "Frontend"],
    outcomeKpis: [
      { metric: "Signups", before: "—", after: "+35%" },
      { metric: "Docs LCP", before: "1.9s", after: "1.0s" },
      { metric: "Support tickets", before: "—", after: "−18%" },
    ],
    outcomeVitals: [ { k: "CLS", v: "0.00" } ],
    experiments: [
      "CTA placement in docs",
      "Sticky ToC thresholds",
      "Copy blocks vs. buttons in docs",
    ],
    learnings: [ "Self‑serve docs reduce basic support questions." ],
    risks: [
      "Bulk actions causing unintended changes — mitigated with undo, audit logs, and confirmations.",
      "Real‑time edits colliding — mitigated with conflict detection.",
    ],
    outcomeWins: [
      "Signups +35% after narrative refresh",
      "Docs LCP 1.9s → 1.0s",
      "Support volume decreased measurably",
    ],
    outcomeDetails: [
      "Outcome‑led narrative clarified value quickly",
      "Sticky ToC enabled quick topic scanning",
      "Zero layout shift improved perceived polish",
      "Event tracking identified high‑intent sections",
      "Docs IA reduced basic support tickets",
      "Guided CTA flow increased course start completion",
      "Searchable docs improved self‑serve discovery"
    ],
    testimonial: {
      quote: "The story is crisp and the docs are fast. Signups grew while support load fell.",
      name: "Miguel Alvarez",
      title: "Product Lead, Nova Learning",
      avatar: "https://randomuser.me/api/portraits/men/45.jpg",
    },
    instrumentation: [
      "GA4 doc search/engagement events",
      "CTA step tracking across docs",
      "Vercel Analytics for RUM",
    ],
    accessibility: [
      "Semantic headings and landmarks in docs",
      "Keyboard‑friendly ToC + skip links",
      "Accessible code blocks and copy actions",
    ],
  },
  {
    slug: "cinder-crm",
    title: "Cinder CRM",
    category: "Dashboard",
    lede: "Role‑based CRM with bulk actions, keyboard navigation, and instant search.",
    cover: "/work/cinder-crm/cover.jpg",
    previewMp4: "/work/cinder-crm/preview.mp4",
    previewGif: "/work/cinder-crm/preview.gif",
    siteUrl: "#",
    metrics: [{ k: "Tickets", v: "−29%" }, { k: "TTI", v: "0.9s" }, { k: "Uptime", v: "99.9%" }],
    tech: ["Next.js", "RSC", "WebSockets", "Auth", "Elastic"],
    problem: "Reps spent too much time waiting for list views and switching contexts.",
    goals: ["Sub‑second search", "Bulk edit flows", "Reduce support tickets"],
    scope: ["Elastic + prefix search", "Bulk actions", "Inline edit", "Activity timeline"],
    highlights: ["Command‑K actions", "Optimistic UI", "Autosave with conflict detection"],
    resultsNarrative: "Ticket volume fell 29% as common workflows sped up and became predictable.",
    timeline: { kickoff: "2024-06-03", launch: "2024-07-29", weeks: 8 },
    services: ["Product", "Frontend", "Backend", "QA"],
    roles: ["Design", "Frontend", "Backend"],
    outcomeKpis: [
      { metric: "Tickets", before: "—", after: "−29%" },
      { metric: "TTI", before: "1.6s", after: "0.9s" },
      { metric: "Bulk edit completion time", before: "—", after: "−31%" },
    ],
    outcomeVitals: [ { k: "Uptime", v: "99.9%" } ],
    experiments: [
      "Prefix vs. fuzzy search",
      "Bulk action flows",
      "Grid density presets",
    ],
    learnings: [ "Optimistic UI makes bulk edits feel instant and safe." ],
    risks: [
      "Offline queue duplicating events — mitigated with idempotency keys and de‑dupe.",
      "Map performance at fleet scale — mitigated by virtualization and worker threads.",
    ],
    outcomeWins: [
      "Tickets −29% with faster workflows",
      "TTI 1.6s → 0.9s across core lists",
      "Bulk edits now safe via optimistic UI",
    ],
    outcomeDetails: [
      "Prefix search balanced speed & relevance",
      "Optimistic UI with undo increased confidence",
      "Inline edits reduced navigation churn",
      "Trace sampling gave visibility without cost spikes",
      "Roving tabindex grid improved keyboarding",
      "Shortcut discoverability via onboarding tips",
      "Autosave reduced data‑loss incidents in long edits"
    ],
    testimonial: {
      quote: "Lists load instantly and bulk edits feel safe. Our support tickets dropped noticeably.",
      name: "Emily Zhang",
      title: "Sales Operations, Cinder CRM",
      avatar: "https://randomuser.me/api/portraits/women/33.jpg",
    },
    instrumentation: [
      "OpenTelemetry across list/record views",
      "Sentry + trace sampling",
      "Usage analytics for bulk actions",
    ],
    accessibility: [
      "Roving tabindex grid for tables",
      "Visible focus & keyboard shortcuts",
      "Announced status for async saves",
    ],
  },
  {
    slug: "glacier-logistics",
    title: "Glacier Logistics",
    category: "Dashboard",
    lede: "Real‑time fleet dashboard with route optimization, alerts, and offline‑safe UI.",
    cover: "/work/glacier-logistics/cover.jpg",
    previewMp4: "/work/glacier-logistics/preview.mp4",
    previewGif: "/work/glacier-logistics/preview.gif",
    siteUrl: "#",
    metrics: [{ k: "Errors", v: "−54%" }, { k: "TTI", v: "1.0s" }, { k: "MTTR", v: "−36%" }],
    tech: ["Next.js", "WebSockets", "Maps", "RSC", "Workers"],
    problem: "Dispatch lacked live status and drivers went dark in low‑signal areas.",
    goals: ["Live map with health signals", "Offline safety", "Actionable alerts"],
    scope: ["Route optimization", "Driver app shell", "Alert rules", "Exportable reports"],
    highlights: ["Map virtualization", "Offline queue + retry", "Geo‑fences with web workers"],
    resultsNarrative: "Incidents surfaced sooner and resolution time dropped by over a third.",
    timeline: { kickoff: "2024-05-13", launch: "2024-07-01", weeks: 7 },
    services: ["Product", "Frontend", "Backend"],
    roles: ["Design", "Frontend", "Backend"],
    outcomeKpis: [
      { metric: "Errors", before: "—", after: "−54%" },
      { metric: "MTTR", before: "—", after: "−36%" },
      { metric: "False alerts", before: "—", after: "−21%" },
    ],
    outcomeVitals: [ { k: "TTI", v: "1.0s" } ],
    experiments: [
      "Offline queue strategies",
      "Geo‑fence thresholds",
      "Driver app offline sync intervals",
    ],
    learnings: [ "Virtualized maps keep interaction smooth at fleet scale." ],
    risks: [
      "Compliance copy errors — mitigated through legal review and content approvals.",
      "Focus styles reducing perceived polish — mitigated with accessible yet subtle rings.",
    ],
    outcomeWins: [
      "Incidents found sooner; MTTR −36%",
      "Error rate −54% with offline queue",
      "Stable 1.0s TTI on dashboard",
    ],
    outcomeDetails: [
      "Virtualized map kept UI smooth at scale",
      "Offline queue ensured actions sync later",
      "Geo‑fences processed in workers for accuracy",
      "Sentry + WS telemetry surfaced flaky links",
      "Color‑blind‑safe palette aided operators",
      "Driver app’s offline‑first shell reduced failed updates",
      "Worker‑computed ETAs improved route accuracy"
    ],
    testimonial: {
      quote: "Dispatch has real-time confidence, even offline. MTTR is down and incidents are resolved faster.",
      name: "Viktor Petrov",
      title: "Fleet Operations Director, Glacier Logistics",
      avatar: "https://randomuser.me/api/portraits/men/37.jpg",
    },
    instrumentation: [
      "Service worker offline queue metrics",
      "Sentry + WebSocket error telemetry",
      "Geo‑event logs streamed to analytics",
    ],
    accessibility: [
      "Color‑blind‑safe map palette",
      "Keyboard panning/zoom and markers",
      "ARIA labels for routes and alerts",
    ],
  },
  {
    slug: "riviera-bank",
    title: "Riviera Bank",
    category: "Authority",
    lede: "Trust‑centric corporate site with accessibility‑first components and compliance pages.",
    cover: "/work/riviera-bank/cover.jpg",
    previewMp4: "/work/riviera-bank/preview.mp4",
    previewGif: "/work/riviera-bank/preview.gif",
    siteUrl: "#",
    metrics: [{ k: "A11y", v: "AA" }, { k: "CWV", v: "Green" }, { k: "Leads", v: "+28%" }],
    tech: ["Next.js", "MDX", "Sitemap", "OG tags", "i18n"],
    problem: "Fragmented components and unclear disclosures reduced trust.",
    goals: ["AA compliance", "Clarity in disclosures", "Green CWV"],
    scope: ["Accessible components", "Compliance pages", "Schema & sitemaps", "Localization"],
    highlights: ["Contrast‑safe palette", "Readable disclosures", "Skip‑links & focus rings"],
    resultsNarrative: "Lead quality improved alongside measurable accessibility gains.",
    timeline: { kickoff: "2024-11-11", launch: "2025-01-06", weeks: 8 },
    services: ["Web", "Accessibility", "SEO"],
    roles: ["Design", "Frontend", "SEO"],
    outcomeKpis: [
      { metric: "Leads", before: "—", after: "+28%" },
      { metric: "A11y", before: "A", after: "AA" },
      { metric: "Form completion rate", before: "—", after: "+19%" },
    ],
    outcomeVitals: [ { k: "CWV", v: "Green" } ],
    experiments: [
      "Disclosure layout",
      "Focus ring styles",
      "Disclosure ordering (short vs. long)",
    ],
    learnings: [ "Readable disclosures improve trust and completion." ],
    risks: [
      "Geo‑pricing tax edge cases — mitigated with VAT/GST configuration tests and fallbacks.",
      "Search caching serving stale promos — mitigated with short TTL and purge hooks.",
    ],
    outcomeWins: [
      "Lead quality +28% with clearer disclosures",
      "AA compliance achieved",
      "Green CWV on all key templates",
    ],
    outcomeDetails: [
      "Contrast‑safe palette across all components",
      "Readable disclosures reduced confusion",
      "Skip links and focus rings improved navigation",
      "Consent Mode v2 respected privacy settings",
      "Structured data improved rich result coverage",
      "Form grouping and inline help raised completion rates",
      "ARIA descriptions clarified compliance notes"
    ],
    testimonial: {
      quote: "Accessibility and clarity were treated as first-class. Trust and lead quality improved.",
      name: "Olivia Bennett",
      title: "Head of Communications, Riviera Bank",
      avatar: "https://randomuser.me/api/portraits/women/59.jpg",
    },
    instrumentation: [
      "GA4 with Consent Mode v2",
      "Search Console + structured data",
      "Performance budgets with Lighthouse CI",
    ],
    accessibility: [
      "Skip links, focus rings, and contrast checks",
      "Accessible disclosures and tables",
      "Keyboard‑safe menus and dialogs",
    ],
  },
  {
    slug: "cobalt-commerce",
    title: "Cobalt Commerce",
    category: "Storefront",
    lede: "Headless storefront with Stripe, multicurrency, and edge‑cached search.",
    cover: "/work/cobalt-commerce/cover.jpg",
    previewMp4: "/work/cobalt-commerce/preview.mp4",
    previewGif: "/work/cobalt-commerce/preview.gif",
    siteUrl: "#",
    metrics: [{ k: "LCP", v: "1.2s" }, { k: "CR", v: "+22%" }, { k: "AOV", v: "+15%" }],
    tech: ["Next.js", "Stripe", "ISR", "Algolia", "i18n"],
    problem: "International buyers couldn’t see local pricing and search was slow off‑region.",
    goals: ["Geo‑pricing", "Fast x‑region search", "Increase CR"],
    scope: ["Stripe multi‑currency", "Edge search cache", "ISR catalog", "VAT/GST display"],
    highlights: ["Locale‑aware pricing", "Edge‑cached search API", "Promo schema"],
    resultsNarrative: "Conversion and average order value rose as friction dropped for international buyers.",
    timeline: { kickoff: "2024-09-02", launch: "2024-10-21", weeks: 7 },
    services: ["Storefront", "Payments", "Search", "SEO"],
    roles: ["Frontend", "Backend", "SEO"],
    outcomeKpis: [
      { metric: "CR", before: "—", after: "+22%" },
      { metric: "AOV", before: "—", after: "+15%" },
      { metric: "LCP", before: "2.3s", after: "1.2s" },
    ],
    outcomeVitals: [ { k: "Geo‑pricing", v: "Enabled" } ],
    experiments: [
      "Edge cache TTLs",
      "Promo schema variants",
      "Promo badge copy (Save vs. Offer)",
    ],
    learnings: [ "Showing local currency early reduces drop‑off." ],
    risks: [
      "Ad traffic mismatch with landing message — mitigated by message test and negative keywords.",
      "Proof reel affecting LCP — mitigated with hover/load strategies and poster frames.",
    ],
    outcomeWins: [
      "CR +22% and AOV +15% post‑launch",
      "LCP 2.3s → 1.2s across catalog",
      "Frictionless geo‑pricing reduced exits",
    ],
    outcomeDetails: [
      "Locale‑aware pricing displayed early",
      "Edge‑cached search accelerated off‑region queries",
      "Promo schema improved discovery",
      "Server‑side Purchase events increased accuracy",
      "Insights data guided merchandising tweaks",
      "Low‑stock badges increased urgency on PDPs",
      "Server‑side attribution improved campaign accuracy"
    ],
    testimonial: {
      quote: "Local currency and fast search removed friction for international buyers. CR and AOV moved up.",
      name: "Lucas Pereira",
      title: "Head of Digital, Cobalt Commerce",
      avatar: "https://randomuser.me/api/portraits/men/44.jpg",
    },
    instrumentation: [
      "Stripe webhooks → server‑side GA4 Purchase",
      "Algolia Insights (view/click/convert)",
      "Currency/display events for QA",
    ],
    accessibility: [
      "Screen‑reader friendly price strings",
      "Keyboardable filters and pagination",
      "Alt text and captions for promos",
    ],
  },
  {
    slug: "beacon-labs",
    title: "Beacon Labs",
    category: "Landing",
    lede: "Single‑focus campaign page with tight message hierarchy and social proof.",
    cover: "/work/beacon-labs/cover.jpg",
    previewMp4: "/work/beacon-labs/preview.mp4",
    previewGif: "/work/beacon-labs/preview.gif",
    siteUrl: "#",
    metrics: [{ k: "TTFB", v: "58ms" }, { k: "CTR", v: "+46%" }, { k: "CPL", v: "−27%" }],
    tech: ["Next.js", "Edge", "Analytics", "Schema.org"],
    problem: "Paid traffic wasn’t converting due to diffuse messaging and slow first byte.",
    goals: ["Own one narrative", "Proof above the fold", "Edge‑rendered TTFB < 80ms"],
    scope: ["Hero & proof band", "Case study tiles", "Analytics plan", "FAQ schema"],
    highlights: ["Auto‑playing proof reel on hover", "Privacy‑safe analytics", "Zero CLS"],
    resultsNarrative: "CTR jumped 46% and cost‑per‑lead fell 27% on the same media spend.",
    timeline: { kickoff: "2025-03-17", launch: "2025-03-31", weeks: 2 },
    services: ["Copy", "Design", "Frontend", "Analytics"],
    roles: ["Strategy", "Design", "Frontend"],
    outcomeKpis: [
      { metric: "CTR", before: "—", after: "+46%" },
      { metric: "CPL", before: "—", after: "−27%" },
      { metric: "TTFB", before: "120ms", after: "58ms" },
    ],
    outcomeVitals: [ { k: "CLS", v: "0.00" } ],
    experiments: [ "Headline focus", "FAQ order", "Proof reel vs. static" ],
    learnings: [ "Single narrative with above‑fold proof improves ad traffic conversion." ],
    risks: [
      "Playground abuse increasing costs — mitigated with rate limits and token caps.",
      "Perceived instability from streaming UI — mitigated with graceful fallback and loading states.",
    ],
    outcomeWins: [
      "CTR +46% on same media spend",
      "CPL −27% with above‑fold proof",
      "TTFB improved to 58ms via Edge",
    ],
    outcomeDetails: [
      "Single‑focus headline improved attention",
      "Above‑fold proof reinforced credibility",
      "Edge rendering cut TTFB for paid traffic",
      "Privacy‑safe analytics verified results",
      "FAQ schema reduced support from ad clicks",
      "Poster frames on proof reels preserved LCP",
      "UTM cohorting revealed creative‑level insights"
    ],
    testimonial: {
      quote: "Owning one narrative changed performance overnight—CTR up, CPL down on the same spend.",
      name: "Nina Patel",
      title: "Campaign Lead, Beacon Labs",
      avatar: "https://randomuser.me/api/portraits/women/64.jpg",
    },
    instrumentation: [
      "Privacy‑safe analytics with custom events",
      "AB test wiring + experiment reports",
      "Schema.org FAQ + breadcrumbs",
    ],
    accessibility: [
      "Heading hierarchy & semantic buttons",
      "High‑contrast CTA and focus outlines",
      "Zero layout shift (CLS 0.00)",
    ],
  },
  {
    slug: "nimbus-ai",
    title: "Nimbus AI",
    category: "SaaS",
    lede: "Inference platform marketing with live playground, SOC2 trust badges, and a crisp docs gateway.",
    cover: "/work/nimbus-ai/cover.jpg",
    previewMp4: "/work/nimbus-ai/preview.mp4",
    previewGif: "/work/nimbus-ai/preview.gif",
    siteUrl: "#",
    metrics: [
      { k: "LCP", v: "1.1s" },
      { k: "Trials", v: "+27%" },
      { k: "CLS", v: "0.00" }
    ],
    tech: ["Next.js", "Tailwind", "Vercel Edge", "PostHog", "Schema.org"],
    problem: "Prospects struggled to connect performance claims to hands‑on results.",
    goals: ["Let visitors try the model in‑page", "Make compliance obvious", "Drive trials"],
    scope: ["Live playground", "Compliance & status page", "Docs gateway", "Event tracking"],
    highlights: ["Web‑safe streaming UI", "Usage‑based pricing explainer", "SOC2 + uptime badges"],
    resultsNarrative: "Trials rose 27% after adding the playground and tightening first‑screen messaging.",
    timeline: { kickoff: "2025-04-14", launch: "2025-05-19", weeks: 5 },
    services: ["Strategy", "Web", "Docs", "Analytics"],
    roles: ["Strategy", "Design", "Frontend", "Analytics"],
    outcomeKpis: [
      { metric: "Trials", before: "—", after: "+27%" },
      { metric: "LCP", before: "1.8s", after: "1.1s" },
      { metric: "Time to first token", before: "420ms", after: "220ms", delta: "−48%" },
    ],
    outcomeVitals: [ { k: "CLS", v: "0.00" } ],
    experiments: [
      "Playground defaults",
      "Badge placement",
      "Status badge placement (header vs. hero)",
    ],
    learnings: [ "Hands‑on demo reduces uncertainty and speeds trial starts." ],
    outcomeWins: [
      "Trials +27% after playground launch",
      "LCP improved 1.8s → 1.1s",
      "Trust signals reduced drop‑off",
    ],
    outcomeDetails: [
      "Playground tied claims to hands‑on results",
      "SOC2 + uptime badges increased trust",
      "Usage‑based pricing explainer reduced confusion",
      "Event stream to PostHog captured engagement",
      "Docs gateway kept users oriented while exploring",
      "Preset prompts lowered time‑to‑first‑success",
      "Live status badge reduced trial hesitancy"
    ],
    testimonial: {
      quote: "Letting prospects try the model in-page removed doubt. Trials rose immediately.",
      name: "Jared Lin",
      title: "VP Product, Nimbus AI",
      avatar: "https://randomuser.me/api/portraits/men/28.jpg",
    },
    instrumentation: [
      "Playground event stream to PostHog",
      "GA4 trials + docs gateway events",
      "Uptime status + badging telemetry",
    ],
    accessibility: [
      "ARIA‑labeled controls in playground",
      "Reduced motion for streaming UI",
      "Accessible docs gateway and nav",
    ],
  },
];